import { Customer, TiffinBill, Payment, BusinessSettings } from '../types';

export const defaultSettings: BusinessSettings = {
  businessName: 'KRISH TIFFIN SERVICE',
  tagline: 'Ghar Jaisa Swad • Pure, Fresh & Hygienic Home Meals',
  primaryPhone: '7798719246',
  secondaryPhone: '9322344302',
  address: 'Shop No. 4, Shree Krishna Residency, Near Model College',
  upiId: '7798719246@upi',
  defaultPrice: 70,
  currencySymbol: '₹',
  invoiceNote: 'Thank you for choosing Krish Tiffin Service! Please clear all pending monthly dues by 5th of each month.',
  ownerName: 'Krish Patil',
};

// Generate realistic date helper for recent days
const getRecentDate = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

export const sampleCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Rahul Sharma',
    number: '9823412345',
    address: 'Room 204, Sai Heritage, College Road',
    defaultPrice: 70,
    defaultMeals: ['Lunch', 'Dinner'],
    status: 'active',
    notes: 'Likes extra rotis with lunch',
    createdAt: getRecentDate(45),
  },
  {
    id: 'cust-2',
    name: 'Priya Deshmukh',
    number: '9765123980',
    address: 'Flat 402, Shivam Apts, MG Road',
    defaultPrice: 75,
    defaultMeals: ['Lunch'],
    status: 'active',
    notes: 'Jain food / No onion garlic on Tuesday',
    createdAt: getRecentDate(30),
  },
  {
    id: 'cust-3',
    name: 'Amit Verma',
    number: '9422019283',
    address: 'Wing B-12, Green Park Society',
    defaultPrice: 70,
    defaultMeals: ['Lunch', 'Dinner'],
    status: 'active',
    notes: 'Regular 2 tiffins on weekends',
    createdAt: getRecentDate(25),
  },
  {
    id: 'cust-4',
    name: 'Sneha Kulkarni',
    number: '8888492011',
    address: 'Girls PG Hostel, Near Metro Station',
    defaultPrice: 65,
    defaultMeals: ['Dinner'],
    status: 'active',
    notes: 'Only Dinner delivery by 8:30 PM',
    createdAt: getRecentDate(20),
  },
  {
    id: 'cust-5',
    name: 'Vikram Joshi',
    number: '9158302918',
    address: 'Infosys Tech Park, Phase 1',
    defaultPrice: 80,
    defaultMeals: ['Lunch', 'Evening Snacks'],
    status: 'active',
    notes: 'Corporate office delivery',
    createdAt: getRecentDate(15),
  },
  {
    id: 'cust-6',
    name: 'Rohan Patil',
    number: '9322344302',
    address: 'Plot 88, Navkar Colony',
    defaultPrice: 70,
    defaultMeals: ['Lunch', 'Dinner'],
    status: 'active',
    notes: 'Monthly advance payer',
    createdAt: getRecentDate(60),
  },
];

export const sampleTiffinBills: TiffinBill[] = [
  // Rahul Sharma (cust-1) - Multiple entries, some paid, some pending
  {
    id: 'bill-101',
    customerId: 'cust-1',
    date: getRecentDate(5),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: true,
    createdAt: getRecentDate(5),
  },
  {
    id: 'bill-102',
    customerId: 'cust-1',
    date: getRecentDate(5),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: true,
    createdAt: getRecentDate(5),
  },
  {
    id: 'bill-103',
    customerId: 'cust-1',
    date: getRecentDate(4),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(4),
  },
  {
    id: 'bill-104',
    customerId: 'cust-1',
    date: getRecentDate(4),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(4),
  },
  {
    id: 'bill-105',
    customerId: 'cust-1',
    date: getRecentDate(3),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-106',
    customerId: 'cust-1',
    date: getRecentDate(3),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-107',
    customerId: 'cust-1',
    date: getRecentDate(2),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-108',
    customerId: 'cust-1',
    date: getRecentDate(2),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-109',
    customerId: 'cust-1',
    date: getRecentDate(1),
    mealTime: 'Lunch',
    price: 70,
    quantity: 2,
    total: 140,
    paidStatus: false,
    note: 'Friend stayed over - 2 meals',
    createdAt: getRecentDate(1),
  },
  {
    id: 'bill-110',
    customerId: 'cust-1',
    date: getRecentDate(1),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(1),
  },
  {
    id: 'bill-111',
    customerId: 'cust-1',
    date: getRecentDate(0),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(0),
  },

  // Priya Deshmukh (cust-2)
  {
    id: 'bill-201',
    customerId: 'cust-2',
    date: getRecentDate(4),
    mealTime: 'Lunch',
    price: 75,
    quantity: 1,
    total: 75,
    paidStatus: true,
    createdAt: getRecentDate(4),
  },
  {
    id: 'bill-202',
    customerId: 'cust-2',
    date: getRecentDate(3),
    mealTime: 'Lunch',
    price: 75,
    quantity: 1,
    total: 75,
    paidStatus: false,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-203',
    customerId: 'cust-2',
    date: getRecentDate(2),
    mealTime: 'Lunch',
    price: 75,
    quantity: 1,
    total: 75,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-204',
    customerId: 'cust-2',
    date: getRecentDate(1),
    mealTime: 'Lunch',
    price: 75,
    quantity: 1,
    total: 75,
    paidStatus: false,
    createdAt: getRecentDate(1),
  },
  {
    id: 'bill-205',
    customerId: 'cust-2',
    date: getRecentDate(0),
    mealTime: 'Lunch',
    price: 75,
    quantity: 1,
    total: 75,
    paidStatus: false,
    createdAt: getRecentDate(0),
  },

  // Amit Verma (cust-3)
  {
    id: 'bill-301',
    customerId: 'cust-3',
    date: getRecentDate(3),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-302',
    customerId: 'cust-3',
    date: getRecentDate(3),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-303',
    customerId: 'cust-3',
    date: getRecentDate(2),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-304',
    customerId: 'cust-3',
    date: getRecentDate(2),
    mealTime: 'Dinner',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-305',
    customerId: 'cust-3',
    date: getRecentDate(1),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(1),
  },
  {
    id: 'bill-306',
    customerId: 'cust-3',
    date: getRecentDate(0),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: false,
    createdAt: getRecentDate(0),
  },

  // Sneha Kulkarni (cust-4)
  {
    id: 'bill-401',
    customerId: 'cust-4',
    date: getRecentDate(2),
    mealTime: 'Dinner',
    price: 65,
    quantity: 1,
    total: 65,
    paidStatus: false,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-402',
    customerId: 'cust-4',
    date: getRecentDate(1),
    mealTime: 'Dinner',
    price: 65,
    quantity: 1,
    total: 65,
    paidStatus: false,
    createdAt: getRecentDate(1),
  },

  // Vikram Joshi (cust-5)
  {
    id: 'bill-501',
    customerId: 'cust-5',
    date: getRecentDate(2),
    mealTime: 'Lunch',
    price: 80,
    quantity: 2,
    total: 160,
    paidStatus: false,
    note: '2 Executive Thalis for office colleagues',
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-502',
    customerId: 'cust-5',
    date: getRecentDate(1),
    mealTime: 'Lunch',
    price: 80,
    quantity: 1,
    total: 80,
    paidStatus: false,
    createdAt: getRecentDate(1),
  },

  // Rohan Patil (cust-6) - Fully paid up
  {
    id: 'bill-601',
    customerId: 'cust-6',
    date: getRecentDate(3),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: true,
    createdAt: getRecentDate(3),
  },
  {
    id: 'bill-602',
    customerId: 'cust-6',
    date: getRecentDate(2),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: true,
    createdAt: getRecentDate(2),
  },
  {
    id: 'bill-603',
    customerId: 'cust-6',
    date: getRecentDate(1),
    mealTime: 'Lunch',
    price: 70,
    quantity: 1,
    total: 70,
    paidStatus: true,
    createdAt: getRecentDate(1),
  },
];

export const samplePayments: Payment[] = [
  {
    id: 'pay-1',
    customerId: 'cust-1',
    amount: 140,
    date: getRecentDate(5),
    paymentMethod: 'UPI/GPay',
    referenceNumber: 'UPI/402819284918',
    note: 'Advance for weekend',
    createdAt: getRecentDate(5),
  },
  {
    id: 'pay-2',
    customerId: 'cust-2',
    amount: 75,
    date: getRecentDate(4),
    paymentMethod: 'PhonePe',
    referenceNumber: 'PP889129841',
    note: 'Online payment',
    createdAt: getRecentDate(4),
  },
  {
    id: 'pay-3',
    customerId: 'cust-6',
    amount: 500,
    date: getRecentDate(3),
    paymentMethod: 'Cash',
    note: 'Cash advance collected during delivery',
    createdAt: getRecentDate(3),
  },
];
